In [1]:
import pandas as pd

### Import Dataset

In [2]:
pv_df_musim_dingin = pd.read_excel("../datasets/raw/pv_musim_dingin.xlsx")
pv_df_musim_gugur = pd.read_excel("../datasets/raw/pv_musim_gugur.xlsx")
pv_df_musim_panas = pd.read_excel("../datasets/raw/pv_musim_panas.xlsx")
pv_df_musim_semi = pd.read_excel("../datasets/raw/pv_musim_semi.xlsx")

In [3]:
wind_df_musim_dingin = pd.read_excel("../datasets/raw/wind_musim_dingin.xlsx")
wind_df_musim_gugur = pd.read_excel("../datasets/raw/wind_musim_gugur.xlsx")
wind_df_musim_panas = pd.read_excel("../datasets/raw/wind_musim_panas.xlsx")
wind_df_musim_semi = pd.read_excel("../datasets/raw/wind_musim_semi.xlsx")

### combine seasonal dataset

In [4]:
df_pv = pd.concat([
    pv_df_musim_dingin,
    pv_df_musim_semi,
    pv_df_musim_panas,
    pv_df_musim_gugur
], axis=0)

In [5]:
df_pv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8753 entries, 0 to 2183
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   年份        8753 non-null   datetime64[ns]
 1   时间        8753 non-null   int64
 2   温度        8753 non-null   float64
 3   湿度        8753 non-null   float64
 4   地面辐射强度    8753 non-null   float64
 5   大气上层辐射强度  8753 non-null   float64
 6   光伏发电      8753 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 547.1 KB

In [6]:
df_wind = pd.concat([
    wind_df_musim_dingin,
    wind_df_musim_semi,
    wind_df_musim_panas,
    wind_df_musim_gugur
], axis=0)

In [7]:
df_wind.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8752 entries, 0 to 2183
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   年份      8752 non-null   datetime64[ns]
 1   时间      8752 non-null   int64
 2   空气密度    8752 non-null   float64
 3   风速      8752 non-null   float64
 4   发电功率    8752 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1)
memory usage: 410.2 KB

### Rename name column

In [8]:
kolom = [
    'timestamp',
    'time',
    'temperature',
    'humidity',
    'surface_radiation',
    'upper_atmospheric_radiation',  
    'output_pv', 
]

df_pv.columns = kolom

In [9]:
df_pv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8753 entries, 0 to 2183
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   timestamp                    8753 non-null   datetime64[ns]
 1   time                         8753 non-null   int64
 2   temperature                  8753 non-null   float64
 3   humidity                     8753 non-null   float64
 4   surface_radiation            8753 non-null   float64
 5   upper_atmospheric_radiation  8753 non-null   float64
 6   output_pv                    8753 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 547.1 KB

In [10]:
kolom = [
    'timestamp',
    'time',
    'air_density',
    'wind_velocity',
    'output_wind', 
]

df_wind.columns = kolom

In [11]:
df_wind.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8752 entries, 0 to 2183
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      8752 non-null   datetime64[ns]
 1   time           8752 non-null   int64
 2   air_density    8752 non-null   float64
 3   wind_velocity  8752 non-null   float64
 4   output_wind    8752 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1)
memory usage: 410.2 KB

In [12]:
df_pv.head()

,timestamp,time,temperature,humidity,surface_radiation,upper_atmospheric_radiation,output_pv
0,2019-12-01 00:00:00,1,-10.687,0.001,0.0,0.0,0.0
1,2019-12-01 01:00:00,2,-10.623,0.001,0.0,0.0,0.0
2,2019-12-01 02:00:00,3,-10.564,0.001,0.0,0.0,0.0
3,2019-12-01 03:00:00,4,-10.954,0.001,0.0,0.0,0.0
4,2019-12-01 04:00:00,5,-11.344,0.001,0.0,0.0,0.0

In [13]:
df_wind.head()

            timestamp  time  air_density  wind_velocity  output_wind
0 2019-12-01 00:00:00     1        1.318          8.285     2578.960
1 2019-12-01 01:00:00     2        1.314          7.990     2379.431
2 2019-12-01 02:00:00     3        1.309          7.685     2162.803
3 2019-12-01 03:00:00     4        1.304          7.547     2068.773
4 2019-12-01 04:00:00     5        1.302          7.058     1740.835

| No | Feature Name | Data Type | Dataset_PV | Dataset_Wind |
| :---: | :--- | :--- | :---: | :---: |
| 1 | timestamp | datetime64 | ✓ | ✓ |
| 2 | time | int64 | ✓ | ✓ |
| 3 | temperature | float64 | ✓ | - |
| 4 | humidity | float64 | ✓ | - |
| 5 | surface_radiation | float64 | ✓ | - |
| 6 | upper_atmospheric_radiation | float64 | ✓ | - |
| 7 | output_pv | float64 | ✓ | - |
| 8 | air_density | float64 | - | ✓ |
| 9 | wind_velocity | float64 | - | ✓ |
| 10 | output_wind | float64 | - | ✓ |